version: "3.8"
services:
  client:
    image: nginx
    ports:
      - 80:80
    volumes:
      - ./front-end:/usr/share/nginx/html
  app:
    build:
      context: .
    platform: linux/x86_64
    volumes:
      - ./Upload:/Upload

    environment:
      #Database Connection
      SPRING_DATASOURCE_DRIVE_CLASS_NAME: "org.postgresql.Driver"
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:8880/wedrive"
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "Admin@1234"

      #JPA Config
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: "org.hibernate.dialect.PostgreSQLDialect"
      SPRING_JPA_HIBERNATE_DDL_AUTO: "update"
      SPRING_JPA_SHOW_SQL: true
      SPRING_JPA_PROPERTIES_HIBERNATE_FORMAT_SQL: true
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8080:8080"
  db:
    image: "postgres:13.1-alpine"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "Admin@1234"
      PGPORT: "8880"
      POSTGRES_DB: "wedrive"
    ports:
      - "8880:8880"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
volumes:
  postgres-data:
  upload-data:
